name: bezpieczna_rodzina
description: "Aplikacja do zadania rekrutacyjnego - Moduł Stref Bezpieczeństwa"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.7

  uuid: ^4.5.1

  # State Management
  flutter_bloc: ^8.1.3

  # Routing
  go_router: ^13.2.0

  # Dependency Injection
  get_it: ^7.6.7

  # Networking
  dio: ^5.4.1

  # Models & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Maps and Geolocation
  google_maps_flutter: ^2.5.3

  # Internationalization
  intl: ^0.20.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  integration_test:
    sdk: flutter

  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true